[www]
user = www-data
group = www-data
listen = 127.0.0.1:9000
listen.owner = www-data
listen.group = www-data

; Ondemand process manager - spawns workers on-request and kills them when idle
pm = ondemand
pm.max_children = 5
pm.process_idle_timeout = 10s
pm.max_requests = 500

clear_env = no
catch_workers_output = yes
decorate_workers_output = no
